import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import random
import os

# --------------------------- CONFIG ---------------------------
CSV_FILE = os.path.join(os.getcwd(), 'traffic_counts.csv')
RECORDS_PER_ANALYSIS = 24
HIGH_TRAFFIC_THRESHOLD = 50

# --------------------------- DATA HANDLING ---------------------------
def load_data():
    try:
        df = pd.read_csv(CSV_FILE)
        df['Time'] = pd.to_datetime(df['Time'], errors='coerce')
        return df
    except FileNotFoundError:
        df = pd.DataFrame(columns=['Date', 'Time', 'Cars', 'Bicycles', 'Pedestrians'])
        df.to_csv(CSV_FILE, index=False)
        return df

def add_entry(cars, bicycles, pedestrians, auto=False):
    df = load_data()
    new_entry = pd.DataFrame({
        'Date': [datetime.now().strftime('%Y-%m-%d')],
        'Time': [datetime.now()],
        'Cars': [cars],
        'Bicycles': [bicycles],
        'Pedestrians': [pedestrians],
        'AutoGenerated': [auto]
    })
    df = pd.concat([df, new_entry], ignore_index=True)
    df.to_csv(CSV_FILE, index=False)

def clear_data():
    if os.path.exists(CSV_FILE):
        os.remove(CSV_FILE)
        st.success("✅ All previous traffic data has been cleared!")
    else:
        st.info("No data found to delete.")

# --------------------------- ANALYSIS ---------------------------
def analyze_data(df):
    df['Total'] = df['Cars'] + df['Bicycles'] + df['Pedestrians']
    df['Hour'] = df['Time'].dt.hour
    traffic_by_hour = df.groupby('Hour')['Total'].sum()
    peak_hour = traffic_by_hour.idxmax()
    peak_traffic = traffic_by_hour.max()
    return traffic_by_hour, peak_hour, peak_traffic

# --------------------------- APP ---------------------------
st.set_page_config(page_title="Vision Track", layout="wide")

# --- Header Section ---
st.markdown("""
<div style="background-color:#2E86C1;padding:20px;border-radius:10px">
<h1 style="color:white;text-align:center;">🚦 Vision Track</h1>
<h3 style="color:white;text-align:center;">Real-Time Traffic Monitoring and Analysis with AI</h3>
</div>
""", unsafe_allow_html=True)

# --------------------------- LIVE TOTALS ---------------------------
df = load_data()
total_cars = df['Cars'].sum() if not df.empty else 0
total_bikes = df['Bicycles'].sum() if not df.empty else 0
total_pedestrians = df['Pedestrians'].sum() if not df.empty else 0
total_all = total_cars + total_bikes + total_pedestrians

st.markdown(f"**Live Total Counts:** Cars={total_cars}, Bicycles={total_bikes}, Pedestrians={total_pedestrians}, Total={total_all}")

# --------------------------- MANUAL ENTRY ---------------------------
st.subheader("Manual Traffic Data Entry")
col1, col2, col3 = st.columns(3)
with col1:
    cars = st.number_input("Cars", min_value=0, value=0, step=1)
with col2:
    bicycles = st.number_input("Bicycles", min_value=0, value=0, step=1)
with col3:
    pedestrians = st.number_input("Pedestrians", min_value=0, value=0, step=1)

total_manual = cars + bicycles + pedestrians
if total_manual > HIGH_TRAFFIC_THRESHOLD:
    st.warning(f"⚠️ High traffic alert! Total vehicles: {total_manual}")

if st.button("Record Manual Entry"):
    add_entry(cars, bicycles, pedestrians)
    st.success(f"Manual data recorded: Cars={cars}, Bicycles={bicycles}, Pedestrians={pedestrians}")

# --------------------------- SIMULATE TRAFFIC BUTTON ---------------------------
st.subheader("Simulate Traffic Data for Demo")
if st.button("Simulate Random Traffic Data"):
    cars_sim = random.randint(0, 20)
    bicycles_sim = random.randint(0, 15)
    pedestrians_sim = random.randint(0, 30)
    add_entry(cars_sim, bicycles_sim, pedestrians_sim, auto=True)
    st.info(f"Simulated data added - Cars: {cars_sim}, Bicycles: {bicycles_sim}, Pedestrians: {pedestrians_sim}")

# --------------------------- CLEAR DATA ---------------------------
if st.button("Clear All Previous Data"):
    clear_data()

# --------------------------- DATA DISPLAY ---------------------------
st.subheader("📊 Recorded Traffic Data")
if df.empty:
    st.info("No traffic data recorded yet.")
else:
    st.dataframe(df[['Date', 'Time', 'Cars', 'Bicycles', 'Pedestrians']])

# --------------------------- DATE FILTER ---------------------------
st.subheader("Filter Data by Date")
if not df.empty:
    unique_dates = df['Date'].unique()
    selected_date = st.selectbox("Select Date:", options=unique_dates)
    df_filtered = df[df['Date'] == selected_date]
else:
    df_filtered = df

# --------------------------- LINE CHART ---------------------------
st.subheader("Traffic Trends Over Time")
if not df_filtered.empty:
    fig, ax = plt.subplots(figsize=(6, 3))
    df_filtered_sorted = df_filtered.sort_values('Time')
    df_filtered_sorted.set_index('Time')[['Cars', 'Bicycles', 'Pedestrians']].plot(ax=ax)
    ax.set_xlabel("Time", fontsize=8)
    ax.set_ylabel("Count", fontsize=8)
    ax.set_title("Traffic Counts Over Time", fontsize=10)
    plt.xticks(rotation=45, fontsize=8)
    plt.yticks(fontsize=8)
    plt.tight_layout()
    st.pyplot(fig)

# --------------------------- TRAFFIC ANALYSIS ---------------------------
st.subheader("Traffic Analysis")

# Manual analysis button
if st.button("Run Traffic Analysis Now"):
    if not df_filtered.empty:
        traffic_by_hour, peak_hour, peak_traffic = analyze_data(df_filtered)
        st.markdown(f"**Peak traffic hour:** {peak_hour}:00 → Total vehicles: {peak_traffic}")
        fig2, ax2 = plt.subplots(figsize=(6, 3))
        traffic_by_hour.plot(kind='bar', ax=ax2, color='skyblue')
        ax2.set_xlabel("Hour of Day", fontsize=8)
        ax2.set_ylabel("Total Traffic", fontsize=8)
        ax2.set_title("Traffic Volume by Hour", fontsize=10)
        plt.xticks(rotation=45, fontsize=8)
        plt.yticks(fontsize=8)
        plt.tight_layout()
        st.pyplot(fig2)
    else:
        st.info("No data to analyze for selected date.")

# Automatic analysis every 24+ records
if not df_filtered.empty and len(df_filtered) >= RECORDS_PER_ANALYSIS:
    if 'last_analysis_index' not in st.session_state:
        st.session_state.last_analysis_index = 0

    if len(df_filtered) - st.session_state.last_analysis_index >= RECORDS_PER_ANALYSIS:
        traffic_by_hour, peak_hour, peak_traffic = analyze_data(df_filtered)
        st.session_state.last_analysis_index = len(df_filtered)
        st.markdown(f"**Auto Peak traffic hour:** {peak_hour}:00 → Total vehicles: {peak_traffic}")
        fig3, ax3 = plt.subplots(figsize=(6, 3))
        traffic_by_hour.plot(kind='bar', ax=ax3, color='lightgreen')
        ax3.set_xlabel("Hour of Day", fontsize=8)
        ax3.set_ylabel("Total Traffic", fontsize=8)
        ax3.set_title("Traffic Volume by Hour (Auto)", fontsize=10)
        plt.xticks(rotation=45, fontsize=8)
        plt.yticks(fontsize=8)
        plt.tight_layout()
        st.pyplot(fig3)

# --------------------------- DAILY SUMMARY & AVERAGES ---------------------------
st.subheader("Daily Summary & Average Traffic")
if not df.empty:
    df_summary = df.groupby('Date')[['Cars','Bicycles','Pedestrians']].sum()
    df_summary['Total'] = df_summary.sum(axis=1)
    df_summary['Avg Vehicles'] = df_summary[['Cars','Bicycles','Pedestrians']].mean(axis=1)
    st.dataframe(df_summary)
else:
    st.info("No data available for summary.")

# --------------------------- DOWNLOAD CSV ---------------------------
if not df.empty:
    csv_download = df.to_csv(index=False)
    st.download_button("📥 Download Traffic CSV", csv_download, "traffic_data.csv", "text/csv")
